# Use root/example user/password credentials
version: '2'

services:
  php:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: always
    networks:
      - backend
    container_name: mfMVC
    depends_on:
      - db
   # network_mode: "host"
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html

  db:
    image: mariadb
    restart: always
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: database
    ports:
      - "8889:3306"
    container_name: mariadb


  adminer:
    image: adminer
    restart: always
    networks:
      - backend
    ports:
      - 8090:8080

volumes:
  mysql-data:
networks:
  backend:
    ipam:
      driver: default
      config:
        -   subnet: 172.40.0.0/16
            gateway: 172.40.0.1